apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
    - name: sample-task1
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello Sample task1"
        - name: sleepDuration
          value: 30
    - name: sample-task2
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello Sample task2"
        - name: sleepDuration
          value: 600
    - name: end-task
      runAfter: [ sample-task1, sample-task2 ]
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello  end"
        - name: sleepDuration
          value: 1
