apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params: 
  - name: message
    description: "Message Body"
  tasks:
    - name: sample-task1
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello Sample task1"
    - name: sample-task2
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello Sample task2"
    - name: end-task
      runAfter: [ sample-task1, sample-task2 ]
      taskRef:
        name: sample-task
      params:
        - name: message
          value: "Hello  end"
