apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  - name: message
  resources:
  steps:
    - name: sample-python-task
      image: python:latest
      script: |
        #!/usr/bin/env python3
        
        print("Hello from Python!")

    - name: sample-shell-task
      image: ubuntu:latest
      script: |
        #!/bin/bash
        echo $(params.message)
