apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  - name: message
  - name: sleepDuration
  resources:
  steps:
    - name: sample-python-task
      image: python
      script: |
        #!/usr/bin/env python3
        
        print("Hello from Python!")

    - name: sample-shell-task
      image: ubuntu
      script: |
        #!/bin/bash -x
        echo $(params.message)
        
        apt update -y
        apt upgrade -y
        apt install wget -y
        wget https://raw.githubusercontent.com/sravanlakkimsetti/tekton-samples/main/data.txt
        
        echo "data.txt"
        cat data.txt


        i=0

        while [ $i -lt 35000 ]
        do
          echo $i >> output.txt; i=$(expr $i + 1);
        done

        wc output.txt
        cat output.txt
        cat output.txt|wc
        cat output.txt| tee second.txt
